blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/orgs/citizenweather/discussions
    about: Ask questions and discuss ideas in our community discussions
  - name: Feature Request
    url: https://github.com/orgs/citizenweather/discussions/categories/ideas
    about: Suggest new features or improvements
